# Generated by Django 2.2 on 2020-10-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=32, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(max_length=32, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='money',
            field=models.IntegerField(verbose_name='Payment'),
        ),
    ]
