# Generated by Django 2.2 on 2020-09-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Level One Menu')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='icon')),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='icon',
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='null means no menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='all menu'),
        ),
    ]
