# Generated by Django 2.2 on 2020-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='other name of url'),
        ),
    ]
