# Generated by Django 2.2 on 2020-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default=2, max_length=32, unique=True, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
